<a href="https://colab.research.google.com/github/TheCalculas/Learning-Pytorch/blob/main/Liner_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Linear Regression

In this tutorial, we'll discuss one of the foundational algorithms in machine learning: *Linear regression*. We'll create a model that predicts crop yields for apples and oranges (*target variables*) by looking at the average temperature, rainfall, and humidity (*input variables or features*) in a region. Here's the training data:

![linear-regression-training-data](https://i.imgur.com/6Ujttb4.png)

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

```
yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2
```

Visually, it means that the yield of apples is a linear or planar function of temperature, rainfall and humidity:

![linear-regression-graph](https://i.imgur.com/4DJ9f8X.png)

In [78]:
import numpy as np
import torch

# Training Data

In [79]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [80]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

# Conversion into pytorch tensors

In [81]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [82]:
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [83]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Linear regression manually

In [84]:
weights = torch.randn(2, 3, requires_grad=True) # CREATES A 2X3 MATRIX WITH 2 ROWS AND 3 COLUMNS HAVING WEATHER, TEMP, HUMIDITY
bias = torch.randn(2, requires_grad=True) # CREATES A 2 ROW BIAS FOR THE SAME

print(weights)
print(bias)

tensor([[ 0.0919, -0.2702,  0.4919],
        [ 1.6818,  1.0951, -0.8131]], requires_grad=True)
tensor([0.1702, 1.1229], requires_grad=True)


In [85]:
def model(inputs, weights, bias):
  return inputs @ weights.t() + bias

In [86]:
predictions = model(inputs, weights, bias)

In [87]:
print(predictions)

tensor([[  9.9299, 162.3027],
        [ 16.2410, 198.4970],
        [  0.4939, 247.0237],
        [ 16.1272, 189.6707],
        [ 15.0097, 165.3797]], grad_fn=<AddBackward0>)


In [88]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [89]:
## now the targets are way different from predictions

## Loss Function

In [90]:
def mseLoss(a, b):
  diff = a-b # CALCULATING THE DIFFERENCE
  return torch.sum(diff*diff) / diff.numel() # CALCULATING THE MEAN SQUARE DIFFERNECE
# here we did the diff*diff -> which multiplies with each element itself which makes it positive bro!

In [91]:
loss = mseLoss(predictions, targets)

In [92]:
print(loss) # will calculate the mean square loss

tensor(8462.2910, grad_fn=<DivBackward0>)


## Gradients

In [93]:
loss.backward()

In [94]:
# Gradients for Weights

print(weights)
print(weights.grad)

tensor([[ 0.0919, -0.2702,  0.4919],
        [ 1.6818,  1.0951, -0.8131]], requires_grad=True)
tensor([[-5247.3140, -6672.9805, -3875.1113],
        [ 8860.5986,  8212.0967,  5143.5186]])


In [95]:
with torch.no_grad():
  weights = weights - weights.grad*1e-5
  bias = bias - bias.grad*1e-5

In [96]:
# print(weights)

In [97]:
# loss = mseLoss(predictions, targets)

In [98]:
print(loss)

tensor(8462.2910, grad_fn=<DivBackward0>)


In [101]:
#


Linear Regresssion using Pytorch built in

In [100]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [105]:
from torch.utils.data import TensorDataset as ts

In [106]:
train_ds = ts(inputs, targets)

In [108]:
train_ds[:3] # has the pair of input with the corresponding outputs

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [109]:
from torch.utils.data import DataLoader as dl

In [112]:
batchsize = 4

train_dl = dl(train_ds, batchsize, shuffle=True)

In [113]:
print(train_dl) # now this we have created the data loader which groups the data in batches for easy training