<a href="https://colab.research.google.com/github/TheCalculas/Learning-Pytorch/blob/main/Liner_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Linear Regression

In this tutorial, we'll discuss one of the foundational algorithms in machine learning: *Linear regression*. We'll create a model that predicts crop yields for apples and oranges (*target variables*) by looking at the average temperature, rainfall, and humidity (*input variables or features*) in a region. Here's the training data:

![linear-regression-training-data](https://i.imgur.com/6Ujttb4.png)

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

```
yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2
```

Visually, it means that the yield of apples is a linear or planar function of temperature, rainfall and humidity:

![linear-regression-graph](https://i.imgur.com/4DJ9f8X.png)

In [78]:
import numpy as np
import torch

# Training Data

In [79]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [80]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

# Conversion into pytorch tensors

In [81]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [82]:
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [83]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Linear regression manually

In [84]:
weights = torch.randn(2, 3, requires_grad=True) # CREATES A 2X3 MATRIX WITH 2 ROWS AND 3 COLUMNS HAVING WEATHER, TEMP, HUMIDITY
bias = torch.randn(2, requires_grad=True) # CREATES A 2 ROW BIAS FOR THE SAME

print(weights)
print(bias)

tensor([[ 0.0919, -0.2702,  0.4919],
        [ 1.6818,  1.0951, -0.8131]], requires_grad=True)
tensor([0.1702, 1.1229], requires_grad=True)


In [85]:
def model(inputs, weights, bias):
  return inputs @ weights.t() + bias

In [86]:
predictions = model(inputs, weights, bias)

In [87]:
print(predictions)

tensor([[  9.9299, 162.3027],
        [ 16.2410, 198.4970],
        [  0.4939, 247.0237],
        [ 16.1272, 189.6707],
        [ 15.0097, 165.3797]], grad_fn=<AddBackward0>)


In [88]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [89]:
## now the targets are way different from predictions

## Loss Function

In [90]:
def mseLoss(a, b):
  diff = a-b # CALCULATING THE DIFFERENCE
  return torch.sum(diff*diff) / diff.numel() # CALCULATING THE MEAN SQUARE DIFFERNECE
# here we did the diff*diff -> which multiplies with each element itself which makes it positive bro!

In [91]:
loss = mseLoss(predictions, targets)

In [92]:
print(loss) # will calculate the mean square loss

tensor(8462.2910, grad_fn=<DivBackward0>)


## Gradients

In [93]:
loss.backward()

In [94]:
# Gradients for Weights

print(weights)
print(weights.grad)

tensor([[ 0.0919, -0.2702,  0.4919],
        [ 1.6818,  1.0951, -0.8131]], requires_grad=True)
tensor([[-5247.3140, -6672.9805, -3875.1113],
        [ 8860.5986,  8212.0967,  5143.5186]])


In [95]:
with torch.no_grad():
  weights = weights - weights.grad*1e-5
  bias = bias - bias.grad*1e-5

In [96]:
# print(weights)

In [97]:
# loss = mseLoss(predictions, targets)

In [98]:
print(loss)

tensor(8462.2910, grad_fn=<DivBackward0>)


In [101]:
#


Linear Regresssion using Pytorch built in

In [100]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [105]:
from torch.utils.data import TensorDataset as ts

In [106]:
train_ds = ts(inputs, targets)

In [108]:
train_ds[:3] # has the pair of input with the corresponding outputs

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [109]:
from torch.utils.data import DataLoader as dl

In [112]:
batchsize = 4

train_dl = dl(train_ds, batchsize, shuffle=True)

In [113]:
print(train_dl) # now this we have created the data loader which groups the data in batches for easy training

In [117]:
# iterating in dataloader
for x, y in train_dl:
  print('input', x)
  print('output', y)
  break

# now you can see the batch size of it == 4 hehe

input tensor([[73., 66., 44.],
        [68., 96., 71.],
        [92., 87., 64.],
        [91., 87., 65.]])
output tensor([[ 57.,  69.],
        [104., 118.],
        [ 82., 100.],
        [ 80., 102.]])


## Defining the model

In [121]:
import torch.nn as nn

In [126]:
model = nn.Linear(3, 2) # linear model with 3 input weights and 2 outputs

In [127]:
print(model.weight)

Parameter containing:
tensor([[ 0.4306,  0.3973,  0.1227],
        [-0.5144,  0.3677,  0.1922]], requires_grad=True)


In [128]:
print(model.bias)

Parameter containing:
tensor([-0.2684,  0.2313], requires_grad=True)


In [130]:
print(model.parameters())

<generator object Module.parameters at 0x7c2dead28eb0>


In [131]:
preds = model(inputs)

In [132]:
print(preds)

tensor([[ 63.0607,  -4.4163],
        [ 81.7316,  -1.9170],
        [ 97.5476,  15.9032],
        [ 65.2774, -29.3116],
        [ 76.1728,  13.4941],
        [ 63.0940,  -5.2984],
        [ 81.4571,  -2.0925],
        [ 98.1009,  15.5810],
        [ 65.2441, -28.4295],
        [ 75.8649,  14.2006],
        [ 62.7861,  -4.5918],
        [ 81.7650,  -2.7991],
        [ 97.8221,  16.0788],
        [ 65.5853, -30.0182],
        [ 76.1394,  14.3762]], grad_fn=<AddmmBackward0>)


## Loss Functions

In [133]:
import torch.nn.functional as F

In [135]:
loss_fun = F.mse_loss

In [136]:
loss = loss_fun(model(inputs), targets)

In [138]:
print(loss) # kaafi zaada aa rha hai ye toh

tensor(4853.7632, grad_fn=<MseLossBackward0>)


In [140]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5) ## ye hai ek optimizer jisse batches mein aate hai naaki poore aati hai cheezein

In [142]:
def fit(num_epoch, model, loss_fun, opt, train_dl):
  for epoch in range(num_epoch):

    for x, y in train_dl:


      pred = model(x)
      loss = loss_fun(pred, y)

      # Compute the gradient
      loss.backward()
      opt.step() ## Update the parameters using gradients
      opt.zero_grad() ## Reset the gradients

    if (epoch+1)%10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epoch, loss.item()))


In [145]:
fit(500, model, loss_fun, opt, train_dl)

Epoch [10/500], Loss: 0.9325
Epoch [20/500], Loss: 1.0349
Epoch [30/500], Loss: 0.9695
Epoch [40/500], Loss: 1.4352
Epoch [50/500], Loss: 1.4363
Epoch [60/500], Loss: 0.9396
Epoch [70/500], Loss: 0.9646
Epoch [80/500], Loss: 0.8911
Epoch [90/500], Loss: 1.0686
Epoch [100/500], Loss: 1.4158
Epoch [110/500], Loss: 0.7495
Epoch [120/500], Loss: 1.0795
Epoch [130/500], Loss: 0.9165
Epoch [140/500], Loss: 0.6425
Epoch [150/500], Loss: 1.0374
Epoch [160/500], Loss: 0.9677
Epoch [170/500], Loss: 0.9948
Epoch [180/500], Loss: 0.8527
Epoch [190/500], Loss: 1.1650
Epoch [200/500], Loss: 1.3377
Epoch [210/500], Loss: 1.5873
Epoch [220/500], Loss: 1.3726
Epoch [230/500], Loss: 0.7121
Epoch [240/500], Loss: 1.5623
Epoch [250/500], Loss: 1.6495
Epoch [260/500], Loss: 0.6739
Epoch [270/500], Loss: 1.1712
Epoch [280/500], Loss: 0.7994
Epoch [290/500], Loss: 0.7527
Epoch [300/500], Loss: 1.5964
Epoch [310/500], Loss: 0.9407
Epoch [320/500], Loss: 1.2737
Epoch [330/500], Loss: 1.4052
Epoch [340/500], Lo

In [148]:
preds = model(inputs)

In [153]:
print(preds)

print(targets )

tensor([[ 56.9172,  70.4917],
        [ 82.0746, 100.5816],
        [118.2206, 132.8764],
        [ 20.8365,  37.8201],
        [101.8647, 118.5596],
        [ 55.6728,  69.4118],
        [ 81.9329, 100.6752],
        [118.5189, 133.4755],
        [ 22.0809,  38.9000],
        [102.9675, 119.7332],
        [ 56.7756,  70.5853],
        [ 80.8301,  99.5017],
        [118.3623, 132.7827],
        [ 19.7337,  36.6466],
        [103.1091, 119.6395]], grad_fn=<AddmmBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])
